// <auto-generated />
namespace Apricot.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EmpIdOnComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpIdOnComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201404160655354_EmpIdOnComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
